1. TITLE (EMAIL SPAM USING MACHINE LEARNING)

This Project Aims To Classify SMS/Email Messages as Spam or not Spam using Machine Learning.

2. IMPORT LIBRARIES (CODE)

In [1]:
import pandas as pd 

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

3. LOAD DATASET

In [2]:
df = pd.read_csv("spam.csv", encoding = "latin1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

4. DATASET INFORMATION

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [5]:
df.shape

(5572, 5)

5. DATA CLEANING (CHECK MISSING VALUES, CHECK DUPLICATE RECORDS, REMOVE DUPLICATES)

In [4]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(403)

In [7]:
df = df.drop_duplicates()

In [8]:
df.shape

(5169, 5)

6. SELECT REQUIRED COLOUMNS(Features selection)

In [9]:
df = df[['v1', 'v2']]
df.columns = ['label', 'message']
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

7. CONVERT LABELS INTO NUMERICAL FORM

In [10]:
df['label'] = df['label'].map({'ham':0, 'spam':1})
df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

8. TRAIN TEST SPLIT

In [11]:
X = df['message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size = 0.2,
    random_state = 42
)

In [12]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4135,)
(1034,)
(4135,)
(1034,)

9. TEXT VECTORIZATION USING TF-IDF

In [13]:
vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

10. MODEL TRANING USING NAIVE BAYES (TRAIN MODEL)

In [14]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

11. PREDICTION

In [15]:
y_pred = model.predict(X_test)

12. MODEL EVALUATION (ACCURACY)

In [16]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9555125725338491

In [17]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97       889
           1       1.00      0.68      0.81       145

    accuracy                           0.96      1034
   macro avg       0.98      0.84      0.89      1034
weighted avg       0.96      0.96      0.95      1034

13. TEST CUSTOM MESSAGE

In [18]:
msg = ["Congratulations! you won a free iPhone.Click here now"]

msg_vector = vectorizer.transform(msg)

prediction = model.predict(msg_vector)

if prediction[0] == 1:
    print("Spam Message")
else:
    print("Not Spam Message")

Not Spam Message

14. CONCLUSION 
 
 the email spam detection model was successfully built using machine learning.
 the naive bayes algorithmswas trained on the SMS spam collection dataset and achieved high accuracy in classifying spam and nin spam messages.